language: node_js
node_js:
  - '0.12'
  - '4'

# Needed for node_canvas build
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev

sudo: false
